### ISSUE TITLE
Utilize RFC 6764 for account setup

### ISSUE THREAD

**Issue by dilyanpalauzov** [jobisoft/DAV-4-TbSync#105]
When a new account is created, when the username contains @domain, the software shall use [RFC 6764 Locating Services for Calendaring Extensions to WebDAV (CalDAV) and vCard Extensions to WebDAV (CardDAV)](https://tools.ietf.org/html/rfc6764) and not insist on server name.

E.g. when the username is aaa@aegee.org, the server name shall not be mandatory to provide in the dialog, as it can be obtained by calling in DNS SRV _caldavs._tcp.aegee.org and _carddavs._tcp.aegee.org .

**Comment by jobisoft** [comment]
Could you contribute? This could be triggered by not entering a server URL during automated setup. The chat component of TB has a dns.jsm which should allow to do DNS lookups.

**Comment by dilyanpalauzov** [comment]
I cannot contribute.

**Comment by jobisoft** [comment]
Do you have a server which supports this and could provide a test account for me?

**Comment by dilyanpalauzov** [comment]
RFC 6764 describes two method to find the server based on the domain from the user name:
* Using .well-known/caldav and .well-known/carddav HTTPS addresses of that domain.  This is implemented for the account aaa\<at\>milter.aegee.org, password abc.
* Using DNS SRV and TXT lookups.  This is implemented for the account aaa\<at\>aegee.org, password abc.

**Comment by jobisoft** [comment]
I will have a look next week.

**Comment by jobisoft** [comment]
Nice, I am able to query DNS via javascript. I actually wanted to try this for a long time. I get back this:

```
DNS SRV: [{"prio":0,"weight":1,"host":"mail.aegee.org","port":443,"type":33,"nsclass":0,"ttl":86312}] 
DNS TXT: [{"data":"path=/dav/addressbooks","type":16,"nsclass":0,"ttl":86312}] 

DNS SRV: [{"prio":0,"weight":1,"host":"mail.aegee.org","port":443,"type":33,"nsclass":0,"ttl":86312}] 
DNS TXT: [{"data":"path=/dav/calendars","type":16,"nsclass":0,"ttl":86312}]
```

I did not read the RFC yet. The SRV record gives me the host and the TXT record gives me the remaining path?

About integrating this in the UI of the account creation dialog:
 - I change order of fields and have the username before the server name(s)
 - After the user has entered a user name with @domain, the lookup is done in the background and the result is filled in the server fields 

What do you think?

**Comment by dilyanpalauzov** [comment]
Yes, if TXT record is missing, then .well-known/caldav | .well-known/carddav are tried.  If SRV _caldavs._tcp is missing, then _caldav._tcp is tried.

It is not necessary to implement DNS lookups to stop asking for the host.  For user aaa@milter.aegee.org if the user does not enter a host, the user means milter.aegee.org is the host (no SRV record).  The lookup in the background can take a while: the software has to query
SRV _caldavc._tcp, SRV _caldav._tcp, SRV _carddavs._tcp, SRV _carddav._tcp, and if no SRV records are found (or if SRV records are found), then PROPFIND host/STUB-URL and then, if something is found, not ask the user for hostname.

**Comment by dilyanpalauzov** [comment]
Not that I use Exchange, but for discoveries with [EAS-4-TbSync](https://github.com/jobisoft/EAS-4-TbSync), a SRV lookup can also be used: https://blogs.technet.microsoft.com/rmilne/2014/10/02/how-to-check-exchange-autodiscover-srv-record-using-nslookup/ , if not yet utilized.  As least I do not see in the sources of EAS-4-TbSync the words `_tcp` or `_autodiscover`. For domain exampleY.net, get the Exchange host from DNS SRV _autodiscover._tcp.exampleY.net .

Sample records are SRV _autodiscover._tcp.hs-ruhrwest.de or SRV _autodiscover._tcp.sit.fraunhofer.de .

**Comment by jobisoft** [comment]
There is an issue open for that request. 
https://github.com/jobisoft/EAS-4-TbSync/issues/17

So far there was no simple way to do DNS lookups from javascript, so this staled. With TB68, we have DNS.jsm which will make this possible as well.

**Comment by dilyanpalauzov** [comment]
Once this is implemented, replace in dav.string “status.service-discovery-failed=sabre/dav service discovery failed for this server.” to “Service discovery per RFC 6764 failed for this domain.”

**Comment by jobisoft** [comment]
Did you remove the DNS entries? For example for

```
_caldavs._tcp.milter.aegee.org
```

I no longer get TXT ir SRV records?

**Comment by dilyanpalauzov** [comment]
This record never existed, you can use `SRV+TXT _caldavs._tcp.aegee.org`.

**Comment by jobisoft** [comment]
Strange. here
https://github.com/jobisoft/DAV-4-TbSync/issues/105#issuecomment-529144926

you said it was implemented for 

aaa<at>milter.aegee.org.

Doesn't that mean, I have to query `_caldavs._tcp.milter.aegee.org`?

**Comment by jobisoft** [comment]
Damn. I read that wrong. You are correct. Sorry.

**Comment by dilyanpalauzov** [comment]
I wrote:
“
RFC 6764 describes two method to find the server based on the domain from the user name:

* Using .well-known/caldav and .well-known/carddav HTTPS addresses of that domain. This is implemented for the account aaa<at>milter.aegee.org, password abc.
* Using DNS SRV and TXT lookups. This is implemented for the account aaa<at>aegee.org, password abc.
”

This means DNS SRV lookup is not implemented for milter.aegee.org.   milter.aegee.org implements one, out of two, of the lookup records and aegee.org implemented at the time I wrote this only the DNS SRV lookup method, but today implements both methods.

**Comment by jobisoft** [comment]
yep, my bad, read that wrong, sorry.

**Comment by jobisoft** [comment]
Thinking about how to implement this in UI. I do not want to add another setup option, but want to merge this into the current automatic setup. 

* when automatic setup is selected only account name & username fields are shown
* user enters a username, that DOES NOT contain a `@domain.tld` part:
  + the server + password fields are unhidden and the process continues as now:
    + user enters a single server url
    + TbSync is trying well-known urls on provided server and either fails or succeeds
* user enters a username, that DOES contain a `@domain.tld` part:
  + TbSync runs all DNS queries in parallel
  + if values have been found, unhide password field (show the found server info? readonly?)
  + if values have NOT been found, server + password fields are unhidden and the process continues as now (see above), but server is prefilled with `@domain.tld` (not readonly)

Also, I would do the DNS lookup even in manual mode (if username contains `@domain.tld`) and prefill the server fields with the found values, but user can change them as he likes.

What do you think?

**Comment by dilyanpalauzov** [comment]
If the user enters username with domain and no hostname, then the setup procedure gives its best.  Otherwise the setup procedure gets stuck, until either a domain behind the username is entered, or hostname is entered.  The setup procedure gets also stuck, if the domain after the username does not offer RFC 6764 discovery, in which case the user must provide user name.

As the discovery mandates whether HTTPS shall be used, the user shall not have influence on this.

The process above does not articulate one step: if no DNS records are available for a domain, but https://domain/.well-known/caldav are present, the CUA uses that addresses and the user does not have to enter hostname.  From user’s perspective there shall be no difference between getting data with DNS SRV lookup for domain or getting data with HTTP lookup for domain/.well-known/carddav .

Whether the servername is hidden sometimes, is a personal taste.

**Comment by dilyanpalauzov** [comment]
I guess you have read RFC 6764, where is recommended e.g. to try to login with username without domain, if the usermane@domain does not work.

**Comment by jobisoft** [comment]
You mean, if the user provides username@domain, the server should try:
- dns lookups for domain
- if that fails, checks domain/.well-known for https and http for user „username“ and „username@domain“
- if that still fails offers user to enter single server URL and again try well-known urls for long and short username
- if that fails again switch to manual setup and offers user to enter both server urls directly which are then probed directly (without adding well-known) and again trying long and short username
- if that fails, we are stuck

If the user provides just username:
- offer user to enter single server url and try well-known urls for username
- if that fails, also switch to manual setup

**Comment by dilyanpalauzov** [comment]
Almost:

The server tries DNS discovery to obtain a “stub URL”.
If it fails the stub URL is https://domain/.well-known/caldav,carddav .
If it does not exists, the stub URL is http://domain/.well-known/caldav,carddav 

If the stub URL does exist, the CUA tries to login with username@domain,
If the login fails and the stub URL exists, the CUA tries to login with username without domain.

That is, the login without domain is tried even if the stub URL is obtained via DNS (this is in RFC 6764).  And this is just one example why the RFC shall be read, before starting implementing it.

What happens if the domain/server does not offer the RFC 6764 autodiscovery, can be made arbitrary complicated:  Ask for hostname, try with well-known addresses using the hostname, with or without domain, if this fails, ask for stub URL (more or less the same as pricipal URL), try with username with or without domain.

**Comment by jobisoft** [comment]
I was hoping you could provide all the info I need to fulfill your implementation request, without actually having to dig through that RFC, which I probably have no time for.

> If it fails the stub URL is https://domain/.well-known/caldav,carddav .
If it does not exists, the stub URL is http://domain/.well-known/caldav,carddav

I do not understand that. I have DNS querries for caldavs/carddavs as well as  caldav/carddav. That defines wether HTTPS or HTTP is used (I will always prefer HTTPS over HTTP, if both is announced).

If DNS discovery failed, why can I not try /well-know for HTTP and(!) HTTPS but have to stick with HTTP? Is that really part of the RFC?

> If the login fails and the stub URL exists, the CUA tries to login with username without domain.

With "login" you mean a authenticated connection to the well-known or stub endpoint? Yes I will first try the long username and afterwards the short, if the long one failed.

> That is, the login without domain is tried even if the stub URL is obtained via DNS (this is in RFC 6764).

Yeah, I was gonna do that for any connection to the server (well-known or stub like remote.php/dav) regardless of how I got there.

**Comment by dilyanpalauzov** [comment]
1. Try _caldavs._tcp.DOMAIN for SRV and TXT, if SRV fails then
2. Try _caldav._tcp.DOMAIN for SRV and TXT, if SRV fails then
3. Try https://domain/.well-known/caldav , if it fails then
4. Try http://domain/.well-known/caldav

Likewise for CardDAV.

At this moment it shall be clear to the CUA whether HTTP or HTTPS should be used and the user shall not be able to change this (as this only clutters the interface).

I have not said, that when DNS fails everything must be exchanged in clear text.

With login I mean authentication.  Well-known addresses are stub URLs.

**Comment by dilyanpalauzov** [comment]
For the record, for a DNS entry several TXT records can exist and each record can contain several strings.  For some protocols, like DKIM, the TXT strings must be concatenated:
```
$ dig txt k4096._domainkey.aegee.org

"v=DKIM1;k=rsa;p=MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAsXqtdxejqo2sS1/cFUME2CQNaq8MvwcWVrLzD
vKtVnJQpZI3tJfNmRAtPlY5a5qGoWPhjHjahXXjXfVgttA1umomDqr3yCzMIQQxqlh64J5nweVtirL7WTgO6YxsL36YnV42+wx24eIGh1oK0plm3z8IYXkD3LPUMuxmBRUMtYI62mUtZmw6WrK
z9Snv37LXl19" "yYT/UYxQF5xTmjkJLBou6vGQnSS93H/tk4rBLmX65OtL4vqVyjJm1hjwHKQbIhxDXA+Ynbg6+vFKfJ5n9lhn2ZR+DMfPyQuxBkzttBCxOAdXPodz8bYFiXOREfY5U43R1FT
MU7Z3X+2+7irYqqowG3xwJDzzpTLk44hTCUuRI1WviipRZogWZ8FZRAvheK2RTmq7NeT6GWxpkC4v1V7pl9TediBZeIcMuPf+ib2U/LyGKDKZJhW9QOzkCmM4iTM" "FOq1wwhk6L6kZkGSG/V
LOPlKyz2RiTRwOXNleypSuQaZqt/icvOs29VDe/iL2jVlTFD/oJDwix8yxpv5mbakel+xrZi6SpRsABobHsQhcRHIlgCU9BiO1l4+B68/odtlSBB2Kl0kAKuVIe8brGBEiJBDC4jByYqaL/qTf
pGC8BCCVrka/RUK48i3itn3Bdvpb5IyvGdXWzJJhNZSRIsxxcTf5wmr5aSnh58rQrh6sCAwEAAQ=="
```
and the result is interpreted as a single string.

In DNS-SD the strings, that are parts of a single TXT record, represent different components of that record and are not concatenated.  The code does not iterate over all TXT records, and for each TXT records the code does not iterate over each string, to check if the string starts with path=.  In the future, if other fields are added to the TXT record, this code might break.

This is however not a disaster, as in practice there is always one TXT record consisting of a single string.

Considering that entering username@posteo.de will find over DNS the bootstrap URL, the profile posteo.de can be removed.  Likewise for web.de, gmx.net, gmx.com, icloud.com.

**Comment by dilyanpalauzov** [comment]
For the sake of life simplification, if automatic detection does not work, the software shall hint the user to tell its administratior ot utilize RFC 6764.

**Comment by jobisoft** [comment]
Regarding the removal of predefined accounts: I will keep them in for convinience, as users like to have the dedicated icon and feel happy if they see "oh it has direct support for XY". Also this is my only chance to generate revenue, when the companies pay me to get their entry in the list.

For iCloud it even must stay in, as I have a gmx.de address for my icloud account and the lookup would thus fail.

**Comment by jobisoft** [comment]
I uploaded a new beta. I would kindly ask you to give it a few spins. The locales are all wrong and still need to be updated, but I think you can see how it is supposed to work.

I added a final page to the wizard, which will contain a "you are good to go" message and maybe some of the found urls. Only by clicking on Finish the account will be created, so you can go back and forth without actually creating accounts. In the developer console you can see the performed requests.

I had one case (gmx.de) which only returned something for the calendar and nothing for contacts, in which case I show the results to the user directly in "custom" mode and he can choose to just take that, or add a carddav url himself.

![image](https://user-images.githubusercontent.com/5830621/65593555-ffb75380-df90-11e9-8995-d28b6838208d.png)

You may also notice, that I do show a server url field per default and that it looks like it is mandetory:

![image](https://user-images.githubusercontent.com/5830621/65593757-75bbba80-df91-11e9-92ee-d9b7b381ac93.png)

But as soon as you add a domain to the username, the field becomes optional:

![image](https://user-images.githubusercontent.com/5830621/65593722-66d50800-df91-11e9-92a1-8ad5fcbb0376.png)

The password field is optional.
The username is optional, if a server is specified.

**I have not yet implemented trying user@domain and just user as password.**

**Comment by dilyanpalauzov** [comment]
After I enter as username aaa@aegee.org and password abc , click on Next, the assistant shows "choose one of the availbalbe profile:" and no profiles are shown.  So I have to click on Next and then it works.  The wizard shall not ask the user to choose a profile, when no profiles can be chosen and things work fine despite of this.

**Comment by jobisoft** [comment]
that is a bug that I do not see. Can you make sure, all your addons are updated? And restart TB?

**Comment by jobisoft** [comment]
No, that is no bug :-) That is the final page I added, which is currently just a placeholder. I described that in my comment. But that means everything works.

**Comment by dilyanpalauzov** [comment]
Under these circumstance, the setup is not implemented completely, but what is so far finished works as expected.

**Comment by jobisoft** [comment]
yes,yes, i just wanted you to be able to ty out the logic, while i cont. to work on the ui stuff.

**Comment by dilyanpalauzov** [comment]
For aaa@milter.aegee.org thr account shall be HTTP-only.  All the PROPFIND requests over HTTPS are answered with 405 Method Not Allowed (Instead of 401 Not Found).  The addon does not switch to HTTP requests.

**Comment by dilyanpalauzov** [comment]
I think, the distinction between automatic and manual configuration shall be abolished.  The automatic configuration is always triggered and if it does not work, or the user wants to change the discovered settings, the manual configuration is performed as a step of the same process.

DAVx5 offers three configurations:
* Login with email address
* Login with URL and user name
* Login with URL and client certificate

These can be squeezed really to two.  Since DAV-4-Sync does not offer certificate login, it needs to offer one out of these three options.

Moreover, it shall be checked now if what the software does reflects RFC6764.  E.g. the RFC allows bootstripping with a mailto: URI or with a http(s): URI.  In the latter case, the user-info shall be extracted from the http(s)-URI.

What to enter as http-URI, if the user is x33@gmx.zet served at https://xxx.ikloud.kom?  Then the @ must be pct-encoded (propably) and the entry URI is https://x33%40gmx.zet@xxx.ikloud.kom/.  Likely nobody will need this option, except the email proveder and WebDAV providers for a person are different.

**Comment by jobisoft** [comment]
I would like to keep it as it is. If a user knows he wants to da manual setup, beause he has principal urls at hand, I do not want to send him through the automatic setup.

I just released a new beta, where I think I have it right. Can you verify and close this issue?

**Comment by dilyanpalauzov** [comment]
I still cannot setup account for aaa@milter.aegee.org . This is supposed to be HTTP-only account.  The CUA calls httpS://milter.aegee.org/.well-known/caldav , on which the server responds with 405 Method Not Allowed.  The CUA is expected to call then HTTP://milter.aegee.org/.well-known/caldav and establish pure HTTP-connection.  Instead, it freezes and the “Cancel” button does not unfreeze it.

**Comment by jobisoft** [comment]
Thanks for all these corner cases. This is helping me a lot. Thanks for your time you put in testing. Looking into this.

**Comment by jobisoft** [comment]
I fixed the freeze issue and released a new beta. He is requesting http now, but I get redirected to https, which fails with 405 again?

```
Connecting: http://milter.aegee.org/.well-known/caldav network.js:220:15
Redirected: https://milter.aegee.org/.well-known/caldav
```

**Comment by dilyanpalauzov** [comment]
I do not see unencrypted traffic in the “Developer Console”.

**Comment by jobisoft** [comment]
The network stack is following 301/302 instantaneously, you will never see the original request in the console. But I do a request to http, which you can see in debug log.

**Comment by jobisoft** [comment]
you also never see a 301/302 response in the console, as they are hidden from you

**Comment by jobisoft** [comment]
crazy, I do not see that redirect wirh curl. What is wrong with that network stack ... I have to investigate that.

**Comment by dilyanpalauzov** [comment]
Perhaps the “Strict-Transport-Security” header messed up? I just removed it.

**Comment by jobisoft** [comment]
When I look at the redirect flags I hit this:

```
/**
 * This is a special-cased redirect coming from hitting HSTS upgrade
 * redirect from http to https only.  In some cases this type of redirect
 * may be considered as safe despite not being the-same-origin redirect.
 */

const unsigned long REDIRECT_STS_UPGRADE = 1 << 3;
```

Do you have anything like that enabled?

**Comment by jobisoft** [comment]
STS could be that Strict-Transport-Security. Did you reload your server after you removed it?

**Comment by jobisoft** [comment]
It appears, Thunderbird has stored the STS header of your page and is doing that now regardless of the header being there or not. I think that is even the purpose of that header, to ensure https connections. I also learned that "normal" redirects do show up in the console, but not STS redirects.

I had to manually remove your STS header cache from the file `SiteSecurityServiceState.txt` in my Thunerbird profile. I can now setup your account as http only.

Can we close this now?

**Comment by dilyanpalauzov** [comment]
I managed to flush the STS memory and now everything works better.

On the second window in the account setup, where the discovered URLs are shown, the URLs are wider that the width of the window and the width of the window cannot be changed.  So the URLs are shown to the user for confirmation, but the user cannot read the full URLs.

In accounts68.json there is still a variable “https”, I believe it can be removed now.

**Comment by jobisoft** [comment]
New beta is out.

The textboxes are now scrollable but still readonly. I want to keep the size of the window fix regardless of how long the url is. The textbox approach is the best compromise without messing up the UI.

The https account property is still used for migration and as fallback:

https://github.com/jobisoft/DAV-4-TbSync/blob/a970d6eeee70a5b5e1176f7f7abc9c6f5b32dc85/content/includes/sync.js#L130-L134

Note I did an important change with this release: Redirects during setup are now not only followed but actually stored. I think you removed the 405 on https for  aaa@milter.aegee.org, so it runs fine with https again but redirects to http. Old beta stored the original https urls, new beta stores the redirected http urls.

**Comment by jobisoft** [comment]
Ah, damn! I also store urls on temp redirects. That is wrong. Hold on.

**Comment by jobisoft** [comment]
Latest beta now stores permanently redirected urls during setup process.

Would be happy if you could test it.

**Comment by jobisoft** [comment]
I would like to release the beta as stable. It would be great if you could test this one last time.

**Comment by dilyanpalauzov** [comment]
This works now as expected.
