### ISSUE TITLE
TbSync/DAV for Thunderbird 102

### ISSUE THREAD

**Issue by zachvlat** [jobisoft/DAV-4-TbSync#283]
**Release Version for Thunderbird 102:**
https://github.com/jobisoft/TbSync/releases/download/v4.1/TbSync.xpi
https://github.com/jobisoft/DAV-4-TbSync/releases/download/v4.1/DAV-4-TbSync.xpi

Please also read this announcement:

https://github.com/jobisoft/DAV-4-TbSync/wiki/Since-Thunderbird-102,-TbSync-DAV-is-using-native-CardDAV-sync

It will take a couple of days before this lands on addons.thunderbird.net

**Comment by ecotechie** [comment]
Same as zachvlat but on Linux (Neon - KDE) using the Snap version of Thunderbird (102.0.1)

**Comment by MagnetizedFreckles** [comment]
Same, Arch-based Linux distro, using the AppImage version of Thunderbird (102.0.1)

**Comment by ndu2** [comment]
Same here, on linux ubuntu, thunderbird 102.0.1 (snap version).
This versions of thunderbird features calender, CalDAV and CardDAV out of the box. No need for the plugin anymore.

I needed to re-configure:

CalDAV: File -> New -> Calendar -> On the network
CardDAV: On Address Book view, New Address Book -> New Add CardDAV Address Book

**Comment by zachvlat** [comment]
> Same here, on linux ubuntu, thunderbird 102.0.1 (snap version). This versions of thunderbird features calender, CalDAV and CardDAV out of the box. No need for the plugin anymore.
> 
> I needed to re-configure:
> 
> CalDAV: File -> New -> Calendar -> On the network CardDAV: On Address Book view, New Address Book -> New Add CardDAV Address Book

It also wokred for me, but I don't know if it fetched everything because it worked or because the contacts/tasks/calender were already there (it was not a fresh install of thunderbird). I have to keep an eye on this, for now.

**Comment by doctorcomputergenova** [comment]
please update the plugin for thunderbird 102.*.*

**Comment by ndu2** [comment]
> please update the plugin for thunderbird 102._._

see above, you don't need the plugin anymore

**Comment by jobisoft** [comment]
For those who still want to use the simplified setup of CalDAV/CardDAV resources, I have updated TbSync/DAV for Thunderbird 102.

A preview:
[TbSync-beta.zip](https://github.com/jobisoft/DAV-4-TbSync/files/9616447/TbSync-beta.zip)
[DAV-4-TbSync.zip](https://github.com/jobisoft/DAV-4-TbSync/files/9616448/DAV-4-TbSync.zip)

Please also read this announcement:
https://github.com/jobisoft/DAV-4-TbSync/wiki/Since-Thunderbird-102,-TbSync-DAV-is-using-native-CardDAV-sync

Since I am only using native sync capabilities, there is not much which can go wrong with this preview. I will release it to the public, after having received some feedback.

**Comment by to82** [comment]
Thanks for the update. I wanted to test it right away, but unfortunately the integration of CalDAV address books does not work. We have an address book in Nextcloud with distribution lists. If I now add a new account, I get the address book offered, but unfortunately it remains empty. TBSync had so far the checkbox "Synchronize contact groups as lists". Is this the reason?

**Comment by jobisoft** [comment]
Yes, as stated here (https://github.com/jobisoft/DAV-4-TbSync/wiki/Since-Thunderbird-102,-TbSync-DAV-is-using-native-CardDAV-sync) TbSync is now using native CardDAV sync. The feature you need should be added to Thunderbird directly.

**Comment by to82** [comment]
Well the problem is that it doesn't work with Thunderbird itself right now. If TBSync is just a different interface, but the result remains the same, then unfortunately this does not help us. That would be very sad, since it worked wonderfully so far. Thunderbird itself doesn't cope with CardDAV sync of distribution lists, only single contacts are possible. As far as I know.

**Comment by jobisoft** [comment]
Sorry that I cannot help you. It is beyond reason to maintain my old sync code (it does not work with 102 and requires almost complete rewrite). Your best bet is to file a bug with Thunderbird and get it fixed.

https://bugzilla.mozilla.org/enter_bug.cgi?product=Thunderbird&component=Address%20Book

**Comment by hellsbelz** [comment]
I've tested the betas right away with my icloud account account in order to sync down the contacts. The setup was straight forward, but the adressbook created by TbSync remains empty, although the sync is reported to be OK. 

Furthermore I noticed, that I even cannot add a contact manually (the button is grey). And, within the adressbooks properties, the URL is empty. 

I'm not sure, if I my procedure was correct. Thus I tried to add a native TB Card-DAV-adressbook using the generic URL contacts.icloud.com and an application specific pasword, but got "condection failed".

**Comment by jobisoft** [comment]
@hellsbelz : Thanks for the report. I made a mistake in the last optimization. I updated the DAV file of the [first preview](https://github.com/jobisoft/DAV-4-TbSync/issues/283#issuecomment-1253630696) (from 2.1 to 2.2)

**Comment by to82** [comment]
Thanks for the update. Synchronization with individual contacts now works without problems. Distribution lists / contact groups still not. I will try to contact the Thunderbird team to see if they can do something about the CardDAV integration.

**Comment by chaos-prevails** [comment]
Dear John,
thanks so much for the update, despite your lack of time, and change of priorities (congrats btw!)! I will test right-away :)

I think this topic came up sometime in the past: integrating TBSync functionality into TB right away.

But so far there is no "bug-report" on bugzilla about this ("TBSync" search didn't result in anything).

If there is really none, would it make sense to start a feature request whether this could be integrated into the upcoming TB release next year? Maybe the TBsync-cal*setup should be added in the account settings of an identity, but accessing the interface to add/remove ca*dav resources should also be available directly from the calendar, address book?

**Comment by jobisoft** [comment]
There are no real plans at the moment. 

The first step is to provide WebExtension APIs for add-ons to add calendars and address book providers, so the TbSync provider add-ons no longer need to use legacy code. I am actively involved in this and we will get that hopefully in the next TB release.

Once there is a tight integration and these external providers can register themselves with Thunderbird (instead of with "just" TbSync), other core parts of Thunderbird could pick them up, even during the account setup wizard. Mostly thinking about Exchange Active Sync here.

I do not think Thunderbird itself will place vendors or groupware providers directly in the product, this is something which TbSync will continue to serve. Once the provider APIs are available, TbSync will be reduced to a pure configuration UI and can be rewritten as pure WebExtension, without the need to be constantly updated in the future.

**Comment by hellsbelz** [comment]
> @hellsbelz : Thanks for the report. I made a mistake in the last optimization. I updated the DAV file of the [first preview](https://github.com/jobisoft/DAV-4-TbSync/issues/283#issuecomment-1253630696) (from 2.1 to 2.2)

@jobisoft Thanks for the updated DAV file. Now I was able to sync my icloud-contacts.

**Comment by DrYak** [comment]
Trying to test this new version v4.1, but have problems with OAuth2.
I am trying to use the TbSync simplified setup with my Google Calendar.
DAV-4-TbSync correctly recognises the mail suffix and doesn't request a server URL (glancing at logs, it's correctly using `https://apidata.googleusercontent.com/caldav/v2/`).
But then it insists on using a password. I cannot switch to OAuth2. And using an App password fails, too.
Are there known problems with the new DAV engine built-in core Thunderbird and with OAuth2?

(Meanwhile, no problem with the iCloud DAV + app password. It seems to be Google-specific)

**Comment by jobisoft** [comment]
I no longer support Google. It has been set to experimental support in 91 and removed in 102.

**Comment by jobisoft** [comment]
@DrYak : In addition to my last statement: If you are able to setup google address books and google calenders with the built-in wizards, I could see if I can redirect to the core authentication methods. I used to have my own OAUTH implementation, which has been removed in 102.

**Comment by jobisoft** [comment]
> @DrYak : In addition to my last statement: If you are able to setup google address books and google calenders with the built-in wizards, I could see if I can redirect to the core authentication methods. I used to have my own OAUTH implementation, which has been removed in 102.

Hm. Does not seem to work.

**Comment by DrYak** [comment]
I gave the Thunderbird's "new calendar" wizard a try and it worked directly:
 - just gave my username (the gmail address)
 - wizard auto detected the adrress
 - wizard lists all the calendar available.
 
 So, huh, well, turns out base Thunderbird solves everything I need.

**Comment by jobisoft** [comment]
Perfect. As I said numerous times, you no longer need TbSync/DAV, but there are users who like the simplified setup (and TB cannot yet setup iCloud).

**Comment by sunjam** [comment]
So, my understanding is that Tbsync lets us synchronize both contacts and calendars at the same time.  I like it a lot, btw.  What are the other differences to the new tb102 design?  I suppose worth updating the documentation.

Thanks for this project!

**Comment by chaos-prevails** [comment]
> To avoid dataloss, I will release TbSync for Thunderbird 102 only after https://bugzilla.mozilla.org/show_bug.cgi?id=1792399 has been backported to Thunderbird 102.

thanks, would you have any ETA of this backport to TB102, being part of the dev-team?

if we add the TbSync addon manually to TB102 through the xpi file, and you later on release TbSync on addons.thunderbird.net, will those Thunderbird 102 deployments "pickup" automatically any TbSync updates from the addon repository? (not sure if an identical id in the manifest would be enough for this).

**Comment by jobisoft** [comment]
> if we add the TbSync addon manually to TB102 through the xpi file, and you later on release TbSync on addons.thunderbird.net, will those Thunderbird 102 deployments "pickup" automatically any TbSync updates from the addon repository? (not sure if an identical id in the manifest would be enough for this).

Yes

> thanks, would you have any ETA of this backport to TB102, being part of the dev-team?

No. The assigned developer issues the backport request based on feedback how the patch reacted on Daily/Beta. I think it is only on Daily now and will reach Beta either on next merge (2022-10-17) or is manually uplifted beforehand. Best is to test and provide feedback in the bug. Giving the data loss nature, it could be uplifted faster if there is enough positive feedback. But it has to go through Beta and cannot be directly applied to ESR.

**Comment by jobisoft** [comment]
Note that this bug also affects any CardDAV address book which you have set up manually, without TbSync.

**Comment by chaos-prevails** [comment]
thanks, we are having contacts with multiple categories, but we are using cardbook. It would be great if more functionality can be included in the built in addressbook in future TB-versions, but TbSync with the easy show/hide of (shared) calendars for endusers was the missing piece to migrate towards TB102.

**Comment by jobisoft** [comment]
> thanks, we are having contacts with multiple categories, but we are using cardbook. It would be great if more functionality can be included in the built in addressbook in future TB-versions, but TbSync with the easy show/hide of (shared) calendars for endusers was the missing piece to migrate towards TB102.

https://bugzilla.mozilla.org/show_bug.cgi?id=1764184#c16

**Comment by phoenix147** [comment]
Seems this is fixed in Thunderbird 102.3.3
https://hg.mozilla.org/releases/comm-esr102/rev/63256dcf0c4a

**Comment by jobisoft** [comment]
This fixed TB eating your categories, but we still do not show them in the interface. We are working on it.

**Comment by jobisoft** [comment]
Released on ATN.
